name: Build iOS App

on:
  push:
    branches: [ "main" ] # Vagy "master", attól függ mi a fő ágad neve

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0' # Vagy amilyen verzió kell az appodhoz

      - name: Build and Archive
        # Itt cseréld ki a "NevedAppja.xcodeproj"-ot a te fájlod nevére!
        run: |
          xcodebuild archive \
            -project Expense-Tracker.xcodeproj" \
            -scheme "Expense-Tracker" \
            -archivePath "Build/Expense-Tracker.xcarchive" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        run: |
          mkdir Payload
          cp -r "Build/Expense-Tracker.xcarchive/Products/Applications/" Payload/
          zip -r "Expense-Tracker.ipa" Payload
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: Expense-Tracker.ipa
